[package]
name = "cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
command-macros="0.2.9"
tokio = { version = "1.20.1", features = ["full"] }
